### ISSUE TITLE
Absolution/theme needs update for phpbb 3.2

### ISSUE THREAD

**Issue by raykai** [LMOspaceace/forumlegend#3]
Hi just wandering if you could have time to fix it for the Absolution/theme 

updated Absolution theme for phpbb 3.2 can be found at [https://www.phpbb.com/community/viewtopic.php?f=596&t=2391661](https://www.phpbb.com/community/viewtopic.php?f=596&t=2391661)

thx for your time :)

**Comment by LMOspaceace** [comment]
updated :)
